export const USE_CASE_CATEGORIES = [
  { id: "marketing", label: "Marketing" },
  { id: "sales", label: "Sales" },
  { id: "support", label: "Support" },
  { id: "product-ops", label: "Product & Ops" },
  { id: "security", label: "Security" },
];

export const USE_CASES = [
  { id: "multi-channel-ivr", name: "Multi-Channel Inbound Self-Service & IVR/IVA", category: "support", products: ["voice", "studio", "conversation-relay"], description: "Support costs are too high. Reduce first call resolution time, wait time, and ticket backlog with intelligent self-service." },
  { id: "supervisor-coaching", name: "Supervisor Coaching & Insights", category: "support", products: ["flex", "conversation-intelligence"], description: "Limited visibility into agent performance. Improve CSAT, average handle time, and issue resolution." },
  { id: "live-agent-assist", name: "Real-Time Live Agent Assist", category: "support", products: ["flex", "conversation-intelligence"], description: "Human agents lack answers in real time. Improve first call resolution and reduce average handle time." },
  { id: "contextual-handoff", name: "Intelligent Contextual Handoff", category: "support", products: ["taskrouter", "flex"], description: "Customers don't get to the right agent. Reduce wait time and improve issue resolution time." },
  { id: "multi-channel-contact-center", name: "Multi-Channel Contact Center", category: "support", products: ["flex", "messaging", "voice"], description: "Live agents lack a unified workspace for two-way conversations across channels after automated routing." },
  { id: "appointment-scheduling", name: "Appointment Scheduling & Rescheduling", category: "support", products: ["messaging", "voice", "studio"], description: "Scheduling processes are manual. Reduce no-show rate and wait time with automated reminders." },
  { id: "automated-wrap-up", name: "Automated Wrap-Up & Knowledge Capture", category: "support", products: ["conversation-intelligence", "flex"], description: "Agents spend too much time documenting. Reduce average handle time and improve first call resolution." },
  { id: "persistent-conversations", name: "Persistent Conversations & Contextual History", category: "support", products: ["flex", "segment-unify"], description: "Customer context is fragmented. Improve CSAT, first call resolution, and reduce ticket backlog." },
  { id: "observability-monitoring", name: "Real-Time Observability & Compliance Monitoring", category: "support", products: ["event-streams", "conversation-intelligence"], description: "Can't trust AI agents at scale. Monitor first call resolution, average handle time, and issue resolution." },
  { id: "click-to-call", name: "Click to Call", category: "sales", products: ["voice", "flex"], description: "Friction slows sales conversations. Improve first-time buyer conversion rate and reduce sales cycle length." },
  { id: "warm-start-outbound", name: "Warm-Start Outbound Agents", category: "sales", products: ["voice", "conversation-relay", "flex"], description: "Don't want to waste human agent time on leads. Improve call answer rate and conversion." },
  { id: "lead-prioritization", name: "Lead Prioritization & Alerts", category: "sales", products: ["messaging", "voice"], description: "Reps waste time on low-value leads. Reduce sales cycle length and improve call answer rate." },
  { id: "personalized-promotions", name: "Personalized Promotions", category: "sales", products: ["segment-engage", "messaging", "sendgrid"], description: "Offers feel generic and ineffective. Improve conversion, ROAS, and upsell rates." },
  { id: "automated-surveys", name: "Automated Surveys & NPS", category: "marketing", products: ["messaging", "sendgrid", "studio"], description: "Lack customer feedback and insights. Track churn rate, CSAT/NPS, and business productivity." },
  { id: "drip-lifecycle", name: "Drip & Lifecycle Campaigns", category: "marketing", products: ["segment-engage", "messaging", "sendgrid"], description: "Low engagement across customer lifecycle. Improve conversion, reduce churn, boost deliverability." },
  { id: "ad-spend-optimization", name: "Ad Spend Optimization", category: "marketing", products: ["segment-engage", "messaging"], description: "Marketing spend isn't delivering ROI. Improve ROAS and reduce customer acquisition cost." },
  { id: "mass-promotions", name: "Mass Promotions", category: "marketing", products: ["messaging", "sendgrid", "marketing-campaigns"], description: "Need to reach customers at scale. Boost conversion, upsell, and deliverability rates." },
  { id: "loyalty-rewards", name: "Loyalty & Rewards", category: "marketing", products: ["messaging", "sendgrid", "segment-engage"], description: "Struggling to retain existing customers. Improve deliverability, upsell, and repeat purchase rates." },
  { id: "abandon-cart-winback", name: "Abandon Cart & Winback", category: "marketing", products: ["segment-engage", "messaging", "sendgrid"], description: "Lost revenue from abandoned journeys. Recover conversion, upsell, and reduce churn." },
  { id: "mass-alerts", name: "Mass Alerts & Notifications", category: "marketing", products: ["messaging", "sendgrid", "voice"], description: "Need to communicate urgent updates. Improve read rate, incident response, reduce compliance violations." },
  { id: "new-user-onboarding", name: "New User Onboarding & Activation", category: "product-ops", products: ["messaging", "sendgrid", "verify"], description: "New users drop off or fail to complete setup. Improve activation rate and opt-in rate." },
  { id: "transaction-alerts", name: "Account & Transaction Specific Alerts", category: "product-ops", products: ["messaging", "sendgrid", "voice"], description: "Customers miss critical account updates. Reduce churn, fraud incidents, improve deliverability." },
  { id: "unified-profiles", name: "Unified Profiles & Identity Management/Resolution", category: "product-ops", products: ["segment-connections", "segment-unify"], description: "Customer data exists in silos. Reduce fraud, false positives, compliance violations, boost productivity." },
  { id: "consent-preference", name: "Compliant Consent, Preference Management & Secure Segmentation", category: "product-ops", products: ["segment-connections", "privacy-portal", "messaging"], description: "Struggling to manage consent compliance, preference management, or segmentation across channels." },
  { id: "secure-signup", name: "Secure Signup", category: "security", products: ["verify", "lookup"], description: "Fake or fraudulent accounts are created without proper safeguards. Improve activation and signup completion rates." },
  { id: "fraud-detection", name: "Fraud Detection & Mitigation", category: "security", products: ["verify", "lookup"], description: "Fraud losses are increasing. Reduce fraud incidents, false positives, and improve deliverability." },
  { id: "secure-login", name: "Secure Login", category: "security", products: ["verify", "lookup"], description: "Logins create friction or risk around account takeovers. Reduce account takeovers, improve OTP success." },
];

export const PRODUCTS = [
  { id: "conversation-memory", name: "Conversation Memory", category: "Conversations" },
  { id: "conversation-orchestrator", name: "Conversation Orchestrator", category: "Conversations" },
  { id: "conversation-intelligence", name: "Conversation Intelligence", category: "Conversations" },
  { id: "conversation-relay", name: "Conversation Relay", category: "Conversations" },
  { id: "messaging", name: "Messaging APIs", category: "Communications" },
  { id: "sendgrid", name: "SendGrid Email", category: "Communications" },
  { id: "voice", name: "Voice API", category: "Communications" },
  { id: "phone-numbers", name: "Phone Numbers", category: "Communications" },
  { id: "elastic-sip-trunking", name: "Elastic SIP Trunking", category: "Communications" },
  { id: "flex", name: "Twilio Flex", category: "Communications" },
  { id: "video", name: "Twilio Video", category: "Communications" },
  { id: "marketing-campaigns", name: "Marketing Campaigns", category: "Communications" },
  { id: "trust-hub", name: "Trust Hub", category: "Communications" },
  { id: "event-streams", name: "Event Streams", category: "Communications" },
  { id: "interconnect", name: "Interconnect", category: "Communications" },
  { id: "taskrouter", name: "TaskRouter", category: "Communications" },
  { id: "sync", name: "Sync", category: "Communications" },
  { id: "twilio-email", name: "Twilio Email", category: "Communications" },
  { id: "verify", name: "Twilio Verify", category: "Authentication" },
  { id: "lookup", name: "Twilio Lookup", category: "Authentication" },
  { id: "segment-connections", name: "Segment Connections", category: "Customer Data" },
  { id: "segment-protocols", name: "Segment Protocols", category: "Customer Data" },
  { id: "segment-unify", name: "Segment Unify", category: "Customer Data" },
  { id: "segment-engage", name: "Segment Engage", category: "Customer Data" },
  { id: "privacy-portal", name: "Privacy Portal", category: "Customer Data" },
  { id: "serverless", name: "Serverless", category: "Builder Tools" },
  { id: "studio", name: "Studio", category: "Builder Tools" },
  { id: "functions", name: "Functions", category: "Builder Tools" },
];

export const COUNTRIES = [
  { code: "Austria", language: "de", label: "Austria" },
  { code: "Belgium", language: "fr", label: "Belgium" },
  { code: "Denmark", language: "da", label: "Denmark" },
  { code: "Finland", language: "fi", label: "Finland" },
  { code: "France", language: "fr", label: "France" },
  { code: "Germany", language: "de", label: "Germany" },
  { code: "Ireland", language: "en", label: "Ireland" },
  { code: "Italy", language: "it", label: "Italy" },
  { code: "Netherlands", language: "nl", label: "Netherlands" },
  { code: "Norway", language: "no", label: "Norway" },
  { code: "Poland", language: "pl", label: "Poland" },
  { code: "Spain", language: "es", label: "Spain" },
  { code: "Sweden", language: "sv", label: "Sweden" },
  { code: "Switzerland", language: "de", label: "Switzerland" },
  { code: "United Kingdom", language: "en", label: "United Kingdom" },
];

export const INDUSTRY_SEGMENTS = [
  { segment: "Retail", verticals: ["Retail", "Hospitality", "Travel & Hospitality", "Transportation", "CPG"] },
  { segment: "High Tech & AI", verticals: ["Technology", "SaaS", "Education", "Media"] },
  { segment: "Healthcare & Life Sciences", verticals: ["Healthcare", "Life Sciences"] },
  { segment: "Financial Services", verticals: ["Financial Services"] },
  { segment: "ISV", verticals: ["Professional Services", "Real Estate", "Nonprofit"] },
];

export const BUYER_PERSONAS = [
  { id: "", label: "Any buyer" },
  { id: "cmo", label: "CMO" },
  { id: "cxo", label: "CXO" },
  { id: "cto", label: "CTO" },
  { id: "ciso", label: "CISO" },
  { id: "cdo", label: "CDO" },
  { id: "cfo", label: "CFO" },
  { id: "marketing_director", label: "VP Marketing" },
  { id: "product_engineering_leader", label: "VP Engineering" },
  { id: "it_director", label: "IT Director" },
  { id: "vp_customer_support", label: "VP Support" },
  { id: "software_developer", label: "Developer" },
];

export const NAV_SECTIONS = [
  { id: "products", label: "Products" },
  { id: "talk-track", label: "Talk track" },
  { id: "regulations", label: "Regulations" },
  { id: "residency", label: "Data residency" },
  { id: "faq", label: "FAQs" },
  { id: "competitors", label: "Competitors" },
  { id: "deletion", label: "Deletion" },
  { id: "persona", label: "Persona" },
  { id: "market-entry", label: "Market entry" },
];
